baseURL: http://docs.sourcebots.co.uk
languageCode: en-gb
title: Sourcebots Documentation
theme: learn

params:
    author: Sourcebots
    description: Sourcebots Documentation
    showVisitedLinks: false
    disableInlineCopyToClipBoard: true
    disableLanguageSwitchingButton: true
    disableAssetsBusting: true

menu:
    shortcuts:
        - name: "<i class='fa fa-github'></i> Github Repo"
          url: https://github.com/sourcebots/docs

        - name: "<i class='fa fa-globe'></i> Website"
          url: https://sourcebots.github.io/website

