baseURL: https://sourcebots.github.io/docs
languageCode: en-gb
title: Sourcebots Documentation
theme: learn
staticDir: static/build

params:
    author: Sourcebots
    description: Sourcebots Documentation
    showVisitedLinks: false
    disableInlineCopyToClipBoard: true
    disableLanguageSwitchingButton: true

menu:
    shortcuts:
        - name: "<i class='fa fa-github'></i> Github Repo"
          url: https://github.com/sourcebots/docs

        - name: "<i class='fa fa-globe'></i> Website"
          url: http://sourcebot

