baseURL: http://docs.sourcebots.co.uk
languageCode: en-gb
title: SourceBots Documentation
theme: learn

params:
    author: Sourcebots
    description: Sourcebots Documentation
    showVisitedLinks: false
    disableInlineCopyToClipBoard: true
    disableLanguageSwitchingButton: true
    disableAssetsBusting: true
    editURL: "https://github.com/sourcebots/docs/tree/master/content/"
    ordersectionsby: "weight"

menu:
    shortcuts:
        - name: "<i class='fa fa-github'></i> Github Repo"
          url: https://github.com/sourcebots/docs

        - name: "<i class='fa fa-globe'></i> Website"
          url: http://sourcebots.co.uk/

enableGitInfo: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
enableEmoji: true
taxonomies: []
pygmentsCodeFencesGuessSyntax: true
disableKinds:
    - taxonomy
    - taxonomyTerm
